Repository today-is-first/oneul, pull requests merged in 2025-05, with the labels that each got.

#107 [Feat] 채팅 DB 연동 작업 및 FE 수정
  backend/demo/src/main/java/store/oneul/mvc/challenge/dao/ChallengeDAO.java
  backend/demo/src/main/java/store/oneul/mvc/challenge/service/ChallengeService.java
  backend/demo/src/main/java/store/oneul/mvc/challenge/service/ChallengeServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/chat/controller/SocketIoController.java
  backend/demo/src/main/java/store/oneul/mvc/chat/dao/ChatDAO.java
  backend/demo/src/main/java/store/oneul/mvc/chat/dto/ChatMessage.java
  backend/demo/src/main/java/store/oneul/mvc/chat/handler/ChatEventHandler.java
  backend/demo/src/main/java/store/oneul/mvc/chat/handler/JoinEventHandler.java
  backend/demo/src/main/java/store/oneul/mvc/chat/service/ChatService.java
  backend/demo/src/main/java/store/oneul/mvc/chat/service/RoomService.java
  backend/demo/src/main/java/store/oneul/mvc/chat/service/SocketIoService.java
  backend/demo/src/main/java/store/oneul/mvc/config/DbConfig.java
  backend/demo/src/main/java/store/oneul/mvc/security/oauth/OAuth2SuccessHandler.java
  backend/demo/src/main/resources/mappers/ChallengeMapper.xml
  backend/demo/src/main/resources/mappers/ChatMapper.xml
  frontend/src/components/challenge/ChallengeList.tsx
  frontend/src/components/chat/ChatHeader.tsx
  frontend/src/components/chat/ChatInput.tsx
  frontend/src/components/chat/ChatMessageItem.tsx
  frontend/src/components/chat/ChatMessageList.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/common/SideBar.tsx
  frontend/src/components/login/OAuthBtn.tsx
  frontend/src/components/regist/RegistForm.tsx
  frontend/src/components/sideBar/SideBar.tsx
  frontend/src/components/sideBar/SidePanel.tsx
  frontend/src/components/sideBar/SidePanelToggleBtn.tsx
  frontend/src/hooks/useApi.ts
  frontend/src/layouts/MainLayout.tsx
  frontend/src/stores/challengeStore.tsx
  frontend/src/stores/socketStore.tsx
  frontend/src/stores/userStore.tsx
  frontend/src/types/ChatMessage.tsx
  frontend/src/utils/date.ts
Labels: 🗃️ BE

#110 [Feat] 피드 작성 DB 연동
  frontend/src/components/challengeDetail/ChallengeFeed.tsx
  frontend/src/components/feed/FeedCreateBtn.tsx
  frontend/src/components/feed/FeedCreateModal.tsx
  frontend/src/components/home/Home.tsx
Labels: 🖥️ FE

#111 [Feat] Swagger 설정
  backend/demo/pom.xml
  backend/demo/src/main/java/store/oneul/mvc/config/SwaggerConfig.java
Labels: 🌐 Infra

#112 [Feat] 챌린지 피드 승인시 workoutLog 자동 생성
  backend/demo/src/main/java/store/oneul/mvc/config/DbConfig.java
  backend/demo/src/main/java/store/oneul/mvc/feed/controller/FeedController.java
  backend/demo/src/main/java/store/oneul/mvc/feed/service/FeedService.java
  backend/demo/src/main/java/store/oneul/mvc/feed/service/FeedServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/workoutLog/dao/WorkoutLogDAO.java
  backend/demo/src/main/java/store/oneul/mvc/workoutLog/dto/WorkoutLogDTO.java
  backend/demo/src/main/java/store/oneul/mvc/workoutLog/dto/WorkoutLogInsertRequestDTO.java
  backend/demo/src/main/resources/mappers/WorkoutLogMapper.xml
  frontend/src/hooks/useApi.ts
Labels: 🗃️ BE

#128 [Feat] Home 페이지 오늘의 운동 컴포넌트 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/chart.ts
  frontend/src/components/chat/ChatMessageList.tsx
  frontend/src/components/common/Card.tsx
  frontend/src/components/common/CardContent.tsx
  frontend/src/components/common/Dialog.tsx
  frontend/src/components/home/Home.tsx
  frontend/src/components/home/MonthlyStats.tsx
  frontend/src/components/home/MyWorkoutDashboard.tsx
  frontend/src/components/home/StreakCalendar.tsx
  frontend/src/components/home/WorkoutModal.tsx
  frontend/src/constants/homeConstants.ts
  frontend/src/types/home.ts
  frontend/src/utils/dateUtils.ts
Labels: 🎨 Design

#132 [Feat] 챌린지 룸 조회 페이지 구현
  frontend/src/App.tsx
  frontend/src/components/challengeSearch/ChallengeSearchPage.tsx
  frontend/src/components/common/Badge.tsx
  frontend/src/components/common/NavBar.tsx
  frontend/src/components/home/CommunityFeed.tsx
  frontend/src/components/home/Home.tsx
  frontend/src/components/home/MyWorkoutDashboard.tsx
Labels: 🎨 Design

#134 [Feat] feed api 연결, primary color 추가
  backend/demo/src/main/java/store/oneul/mvc/feed/dto/FeedDTO.java
  backend/demo/src/main/resources/mappers/FeedMapper.xml
  frontend/src/components/challengeDetail/ChallengeDetailPage.tsx
  frontend/src/components/challengeDetail/ChallengeFeed.tsx
  frontend/src/components/challengeDetail/ChallengeStatus.tsx
  frontend/src/components/challengeDetail/ChellengeDetail.tsx
  frontend/src/components/feed/FeedDetailModal.tsx
  frontend/src/components/feed/FeedUpdateModal.tsx
  frontend/src/components/feed/MateFeedItem.tsx
  frontend/src/components/feed/MateFeedList.tsx
  frontend/src/components/feed/MyFeedCard.tsx
  frontend/src/components/feedCheck/FeedCheckItem.tsx
  frontend/src/components/feedCheck/FeedCheckList.tsx
  frontend/src/components/feedCheck/FeedCheckModal.tsx
  frontend/src/components/feedCheck/FeedCheckTab.tsx
  frontend/src/components/home/MyWorkoutDashboard.tsx
  frontend/src/hooks/useChallenge.ts
  frontend/src/hooks/useFeed.ts
  frontend/src/index.css
  frontend/src/types/Feed.ts
Labels: 🖥️ FE

#136 [Feat] 홈페이지 배너 기능 추가
  frontend/public/imgs/banner/banner1.png
  frontend/public/imgs/banner/banner2.png
  frontend/public/imgs/banner/banner3.png
  frontend/src/components/home/BannerSlider.tsx
  frontend/src/components/home/MyWorkoutDashboard.tsx
  package-lock.json
  package.json
Labels: 🎨 Design

#137 [Feat] 사이드바에 로그인 버튼 추가
  frontend/public/svgs/default-profile.svg
  frontend/src/components/common/LoginBtn.tsx
  frontend/src/components/feed/FeedCreateModal.tsx
  frontend/src/components/home/MyWorkoutDashboard.tsx
  frontend/src/components/sideBar/SideBar.tsx
  frontend/src/components/sideBar/SidePanelToggleBtn.tsx
  frontend/src/layouts/MainLayout.tsx
Labels: 🎨 Design

#141 [Feat] 홈페이지 컴포넌트 DB 연동 / Presigned-URL Get 기능
  backend/demo/src/main/java/store/oneul/mvc/feed/controller/FeedController.java
  backend/demo/src/main/java/store/oneul/mvc/feed/controller/PersonalFeedController.java
  backend/demo/src/main/java/store/oneul/mvc/feed/dao/FeedDAO.java
  backend/demo/src/main/java/store/oneul/mvc/feed/dto/CommunityFeedDTO.java
  backend/demo/src/main/java/store/oneul/mvc/feed/dto/StreakDTO.java
  backend/demo/src/main/java/store/oneul/mvc/feed/service/FeedService.java
  backend/demo/src/main/java/store/oneul/mvc/feed/service/FeedServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/upload/controller/UploadController.java
  backend/demo/src/main/java/store/oneul/mvc/upload/util/S3PresignedUrlGenerator.java
  backend/demo/src/main/resources/mappers/FeedMapper.xml
  frontend/src/App.tsx
  frontend/src/components/feed/FeedCreateModal.tsx
  frontend/src/components/home/CommunityFeed.tsx
  frontend/src/components/home/MyWorkoutDashboard.tsx
  frontend/src/components/home/WorkoutModal.tsx
  frontend/src/constants/homeConstants.ts
  frontend/src/stores/feedStore.tsx
  frontend/src/types/Feed.ts
  frontend/src/types/Streak.ts
Labels: 🖥️ FE, 🗃️ BE

#143 [Feat] CommunityChallenge BE 연동 구현
  backend/demo/src/main/java/store/oneul/mvc/challenge/controller/ChallengeController.java
  backend/demo/src/main/java/store/oneul/mvc/challenge/dao/ChallengeDAO.java
  backend/demo/src/main/java/store/oneul/mvc/challenge/dto/ChallengeDTO.java
  backend/demo/src/main/java/store/oneul/mvc/challenge/service/ChallengeService.java
  backend/demo/src/main/java/store/oneul/mvc/challenge/service/ChallengeServiceImpl.java
  backend/demo/src/main/resources/mappers/ChallengeMapper.xml
  frontend/src/App.tsx
  frontend/src/components/challengeSearch/ChallengeSearchPage.tsx
  frontend/src/constants/challengeSearchContants.ts
  frontend/src/stores/challengeStore.tsx
  frontend/src/types/Challenge.ts
Labels: 🖥️ FE, 🗃️ BE

#158 [Feat] 챌린지 디테일 모달 구현
  backend/demo/src/main/resources/mappers/ChallengeMapper.xml
  frontend/src/App.tsx
  frontend/src/components/challenge/ChallengeList.tsx
  frontend/src/components/challengeDetail/ChellengeDetail.tsx
  frontend/src/components/challengeRegist/ChallengeDetailModal.tsx
  frontend/src/components/challengeSearch/ChallengeSearchPage.tsx
  frontend/src/stores/challengeStore.tsx
  frontend/src/types/Challenge.ts
Labels: 🖥️ FE

#159 [Feat] 결제 orderId 발급 및 Redis 저장 기능 구현
  backend/demo/src/main/java/store/oneul/mvc/challenge/dao/ChallengeDAO.java
  backend/demo/src/main/java/store/oneul/mvc/challenge/service/ChallengeService.java
  backend/demo/src/main/java/store/oneul/mvc/challenge/service/ChallengeServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/config/RedisConfig.java
  backend/demo/src/main/java/store/oneul/mvc/payment/controller/PaymentController.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dto/OrderIdResponse.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dto/PaymentSessionDto.java
  backend/demo/src/main/resources/mappers/ChallengeMapper.xml
Labels: 🗃️ BE

#170 [Feat] 오늘의 인증 챌린지 선택 기능 추가 및 리액트 쿼리 캐싱 개선
  backend/demo/src/main/java/store/oneul/mvc/feed/controller/FeedController.java
  backend/demo/src/main/java/store/oneul/mvc/feed/dao/FeedDAO.java
  backend/demo/src/main/java/store/oneul/mvc/feed/dto/ContentDTO.java
  backend/demo/src/main/java/store/oneul/mvc/feed/service/FeedService.java
  backend/demo/src/main/java/store/oneul/mvc/feed/service/FeedServiceImpl.java
  backend/demo/src/main/resources/mappers/FeedMapper.xml
  frontend/src/components/feed/FeedCreateModal.tsx
  frontend/src/components/feed/FeedUpdateModal.tsx
  frontend/src/components/feed/MyFeedCard.tsx
  frontend/src/components/home/MyWorkoutDashboard.tsx
Labels: 🖥️ FE

#173 [Feat] Toss 결제 승인 기능 구현 및 예외 처리 추가
  backend/demo/src/main/java/store/oneul/mvc/config/GlobalExceptionHandler.java
  backend/demo/src/main/java/store/oneul/mvc/payment/client/TossClient.java
  backend/demo/src/main/java/store/oneul/mvc/payment/config/RestClientConfig.java
  backend/demo/src/main/java/store/oneul/mvc/payment/controller/PaymentController.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dao/PaymentDAO.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dto/PaymentConfirmRequest.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dto/TossConfirmRequest.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dto/TossConfirmResponse.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dto/TossErrorInfo.java
  backend/demo/src/main/java/store/oneul/mvc/payment/exception/PaymentConfirmException.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/TossConfirmService.java
  backend/demo/src/main/java/store/oneul/mvc/payment/usecase/PaymentUsecase.java
  backend/demo/src/main/java/store/oneul/mvc/payment/validator/PaymentValidator.java
  backend/demo/src/main/resources/mappers/PaymentMapper.xml
Labels: 🗃️ BE

#176 [Feat] 피드 디테일 모달 UI 변경 및 홈페이지 피드 클릭 시 디테일 모달 기능 구현
  backend/demo/src/main/java/store/oneul/mvc/feed/controller/FeedController.java
  backend/demo/src/main/java/store/oneul/mvc/feed/dao/FeedDAO.java
  backend/demo/src/main/java/store/oneul/mvc/feed/dto/ChallengeFeedDTO.java
  backend/demo/src/main/java/store/oneul/mvc/feed/service/FeedService.java
  backend/demo/src/main/java/store/oneul/mvc/feed/service/FeedServiceImpl.java
  backend/demo/src/main/resources/mappers/FeedMapper.xml
  frontend/src/components/challengeDetail/ChallengeDetailPage.tsx
  frontend/src/components/challengeDetail/ChallengeFeed.tsx
  frontend/src/components/feed/FeedDetailModal.tsx
  frontend/src/components/home/CommunityFeedItem.tsx
  frontend/src/components/home/CommunityFeedList.tsx
  frontend/src/components/home/MyWorkoutDashboard.tsx
  frontend/src/hooks/useFeed.ts
Labels: 🖥️ FE

#174 [Design] 월간 통계, 스트릭 비율 수정
  backend/demo/src/main/java/store/oneul/mvc/feed/controller/FeedController.java
  backend/demo/src/main/java/store/oneul/mvc/feed/dao/FeedDAO.java
  backend/demo/src/main/java/store/oneul/mvc/feed/dto/ChallengeFeedDTO.java
  backend/demo/src/main/java/store/oneul/mvc/feed/service/FeedService.java
  backend/demo/src/main/java/store/oneul/mvc/feed/service/FeedServiceImpl.java
  backend/demo/src/main/resources/mappers/FeedMapper.xml
  frontend/src/components/challengeDetail/ChallengeDetailPage.tsx
  frontend/src/components/challengeDetail/ChallengeFeed.tsx
  frontend/src/components/feed/FeedDetailModal.tsx
  frontend/src/components/home/CommunityFeedItem.tsx
  frontend/src/components/home/CommunityFeedList.tsx
  frontend/src/components/home/MonthlyStats.tsx
  frontend/src/components/home/MyWorkoutDashboard.tsx
  frontend/src/components/home/StreakCalendar.tsx
  frontend/src/hooks/useFeed.ts
  frontend/src/layouts/MainLayout.tsx
Labels: :bug: Fix

#175 [Feat] 결제 페이지 퍼블리싱 & orderID 요청 api 함수 연결
  frontend/src/App.tsx
  frontend/src/api/payment.ts
  frontend/src/components/challengeRegist/ChallengeDetailModal.tsx
  frontend/src/components/payment/ChallengePaymentPage.tsx
Labels: 🖥️ FE

#177 [Feat] RestClient 설정 정리 및 글로벌 예외 처리 확장
  backend/demo/src/main/java/store/oneul/mvc/config/DbConfig.java
  backend/demo/src/main/java/store/oneul/mvc/config/ErrorCode.java
  backend/demo/src/main/java/store/oneul/mvc/config/GlobalExceptionHandler.java
  backend/demo/src/main/java/store/oneul/mvc/config/RestClientConfig.java
Labels: 🗃️ BE

#178 [Feat] 챌린지 조회 페이지 챌린지 상태 필터 기능 구현
  frontend/src/components/challengeSearch/CategoryTab.tsx
  frontend/src/components/challengeSearch/ChallenegeModeTab.tsx
  frontend/src/components/challengeSearch/ChallengeSearchPage.tsx
  frontend/src/components/challengeSearch/ChallengeSearchRoomItem.tsx
  frontend/src/components/challengeSearch/ChallengeStatusTab.tsx
  frontend/src/constants/challengeSearchContants.ts
Labels: 🖥️ FE, 🎨 Design

#180 [Feat] 채팅 무한 스크롤 기능 구현
  backend/demo/src/main/java/store/oneul/mvc/chat/dao/ChatDAO.java
  backend/demo/src/main/java/store/oneul/mvc/chat/dto/FetchPreviousMessagesRequest.java
  backend/demo/src/main/java/store/oneul/mvc/chat/handler/ChatEventHandler.java
  backend/demo/src/main/java/store/oneul/mvc/chat/service/ChatService.java
  backend/demo/src/main/resources/mappers/ChatMapper.xml
  frontend/src/components/challengeDetail/ChallengeFeed.tsx
  frontend/src/components/chat/ChatMessageList.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/stores/feedStore.tsx
  frontend/src/stores/socketStore.tsx
Labels: 🖥️ FE

#183 [Fix] orderID 포맷수정
  backend/demo/src/main/java/store/oneul/mvc/payment/controller/PaymentController.java
Labels: 🗃️ BE

#185 [Feat] 결제 및 결과에 따른 성공/실패 페이지 생성, 이동 구현
  frontend/src/App.tsx
  frontend/src/api/payment.ts
  frontend/src/components/payment/ChallengePaymentPage.tsx
  frontend/src/components/payment/PaymentFailPage.tsx
  frontend/src/components/payment/PaymentSuccessPage.tsx
  frontend/src/hooks/usePayment.ts
  frontend/src/types/Payment.ts
Labels: 🖥️ FE

#186 [Fix] 챌린지 결제 모듈이 불러와지지 않는 문제
  backend/demo/src/main/java/store/oneul/mvc/challenge/controller/ChallengeController.java
  backend/demo/src/main/resources/mappers/ChallengeMapper.xml
  frontend/src/components/challengeDetail/ChallengeDetailPage.tsx
  frontend/src/hooks/useChallenge.ts
Labels: 🖥️ FE, 🗃️ BE

#187 [Feat] 결제 성공 시 payment 및 challenge_user 저장 및 트랜잭션 실패 감지 로직 추가
  backend/demo/src/main/java/store/oneul/mvc/challenge/dao/ChallengeDAO.java
  backend/demo/src/main/java/store/oneul/mvc/challenge/dto/ChallengeUserDTO.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dao/PaymentDAO.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dto/PaymentDTO.java
  backend/demo/src/main/java/store/oneul/mvc/payment/event/PaymentConfirmedEvent.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/PaymentSaveService.java
  backend/demo/src/main/java/store/oneul/mvc/payment/usecase/PaymentUsecase.java
  backend/demo/src/main/resources/mappers/ChallengeMapper.xml
  backend/demo/src/main/resources/mappers/PaymentMapper.xml
Labels: 🗃️ BE

#188 [Chore] 트랜잭션 서비스 주석 해제
  backend/demo/src/main/java/store/oneul/mvc/payment/usecase/PaymentUsecase.java
Labels: 🗃️ BE

#191 [Feat] Toss 결제 보상 트랜잭션 처리 및 응답 분기 구조 구현
  backend/demo/src/main/java/store/oneul/mvc/payment/calculator/RefundAmountCalculator.java
  backend/demo/src/main/java/store/oneul/mvc/payment/client/TossClient.java
  backend/demo/src/main/java/store/oneul/mvc/payment/controller/PaymentController.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dao/PaymentDAO.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dto/PaymentResultResponse.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dto/RefundReceiptDTO.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dto/TossCancelRequest.java
  backend/demo/src/main/java/store/oneul/mvc/payment/enums/RefundReason.java
  backend/demo/src/main/java/store/oneul/mvc/payment/event/CompensationEventHandler.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/CompensationService.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/CompensationServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/PaymentSaveService.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/PaymentSaveServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/RefundReceiptService.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/RefundReceiptServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/TossCancelService.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/TossCancelServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/TossConfirmService.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/TossConfirmServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/payment/usecase/PaymentUsecase.java
  backend/demo/src/main/java/store/oneul/mvc/payment/validator/PaymentValidator.java
  backend/demo/src/main/resources/mappers/PaymentMapper.xml
Labels: 🗃️ BE

#192 [Feat] 챌린지 가입 BE&FE 로직 구현 및 상황별 분기처리, 챌린지 디테일 모달 수정
  backend/demo/src/main/java/store/oneul/mvc/challenge/controller/ChallengeController.java
  backend/demo/src/main/java/store/oneul/mvc/challenge/dao/ChallengeDAO.java
  backend/demo/src/main/java/store/oneul/mvc/challenge/exception/ChallengeAlreadyJoinedException.java
  backend/demo/src/main/java/store/oneul/mvc/challenge/service/ChallengeService.java
  backend/demo/src/main/java/store/oneul/mvc/challenge/service/ChallengeServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/config/ErrorCode.java
  backend/demo/src/main/java/store/oneul/mvc/config/GlobalExceptionHandler.java
  backend/demo/src/main/resources/mappers/ChallengeMapper.xml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/challenge.ts
  frontend/src/components/Toast/Toast.tsx
  frontend/src/components/Toast/ToastBox.tsx
  frontend/src/components/Toast/ToastList.tsx
  frontend/src/components/challengeDetail/ChellengeDetail.tsx
  frontend/src/components/challengeRegist/ChallengeDetailModal.tsx
  frontend/src/components/challengeSearch/ChallengeSearchPage.tsx
  frontend/src/components/challengeSearch/ChallengeSearchRoomItem.tsx
  frontend/src/components/common/Badge.tsx
  frontend/src/components/payment/PaymentFailPage.tsx
  frontend/src/components/payment/PaymentSuccessPage.tsx
  frontend/src/hooks/useApiHooks.ts
  frontend/src/hooks/useChallenge.ts
  frontend/src/index.css
  frontend/src/types/ApiResponse.ts
  frontend/src/types/Toast.ts
Labels: 🖥️ FE, 🗃️ BE, 🎨 Design

#193 [Feat] 스트릭 클릭 시 피드 뜨는 기능 구현
  frontend/src/components/common/Dialog.tsx
  frontend/src/components/feed/FeedDetailItem.tsx
  frontend/src/components/feed/FeedDetailModal.tsx
  frontend/src/components/home/MyWorkoutDashboard.tsx
  frontend/src/components/home/WorkoutModal.tsx
  frontend/src/index.css
  frontend/src/utils/date.ts
Labels: 🗃️ BE

#197 [Feat] 챌린지 참여 성공시 챌린지 디테일 페이지 이동 구현, 챌린지 데이터 리페치
  frontend/src/components/challengeRegist/ChallengeDetailModal.tsx
  frontend/src/hooks/useChallenge.ts
Labels: 🖥️ FE

#198 [Feat] 마이페이지 퍼블리싱 및 기능 구현
  frontend/src/App.tsx
  frontend/src/components/common/NavBar.tsx
  frontend/src/components/home/CommunityFeedList.tsx
  frontend/src/components/home/FeedItem.tsx
  frontend/src/components/home/FeedList.tsx
  frontend/src/components/home/MyWorkoutDashboard.tsx
  frontend/src/components/mypage/MyChallengeList.tsx
  frontend/src/components/mypage/MyFeedList.tsx
  frontend/src/components/mypage/MyPage.tsx
Labels: 🖥️ FE, 🎨 Design

#199 [Feat] 챌린지 생성 컴포넌트 퍼블리싱
  frontend/src/components/challengeCreate/ChallengeRoomForm.tsx
  frontend/src/components/challengeSearch/ChallegeCreateBtn.tsx
  frontend/src/components/challengeSearch/ChallengeSearchPage.tsx
  frontend/src/components/home/WorkoutModal.tsx
Labels: 🖥️ FE

#200 [Feat] 미시작 챌린지 디테일 페이지 분기처리
  backend/demo/src/main/resources/mappers/ChallengeMapper.xml
  frontend/src/api/api.ts
  frontend/src/components/challengeDetail/ChallengeDetailPage.tsx
  frontend/src/components/challengeDetail/ChallengeFeed.tsx
  frontend/src/components/challengeDetail/ChallengeStatus.tsx
  frontend/src/components/feed/MyFeedCard.tsx
  frontend/src/types/Challenge.ts
Labels: 🖥️ FE

#204 [Feat] 디테일 페이지 세부 디자인 및 표시 내용 수정
  backend/demo/src/main/java/store/oneul/mvc/challenge/dto/ChallengeDTO.java
  backend/demo/src/main/resources/mappers/ChallengeMapper.xml
  frontend/src/components/challengeDetail/ChallengeDetailPage.tsx
  frontend/src/components/challengeDetail/ChallengeFeed.tsx
  frontend/src/components/challengeDetail/ChallengeStatus.tsx
  frontend/src/components/challengeDetail/ChellengeDetail.tsx
  frontend/src/components/feed/FeedCreateBtn.tsx
  frontend/src/components/feed/MyFeedCard.tsx
  frontend/src/types/Challenge.ts
Labels: 🎨 Design

#206 [Feat] 챌린지 생성 기능 구현
  backend/demo/src/main/java/store/oneul/mvc/challenge/controller/ChallengeController.java
  backend/demo/src/main/java/store/oneul/mvc/challenge/service/ChallengeServiceImpl.java
  backend/demo/src/main/resources/mappers/ChallengeMapper.xml
  frontend/src/App.tsx
  frontend/src/components/challengeCreate/ChallengeCreatePage.tsx
  frontend/src/components/challengeCreate/ChallengeRoomForm.tsx
  frontend/src/components/challengeCreate/CustomDateInput.tsx
  frontend/src/components/challengeCreate/PublicToggle.tsx
  frontend/src/components/challengeCreate/SelectBlock.tsx
  frontend/src/components/challengeCreate/TextAreaBlock.tsx
  frontend/src/components/common/InputBlock.tsx
Labels: 🖥️ FE

#208 [Feat] Toss 취소 실패 시 DLQ 적재 및 스케줄링 기반 환불 재시도 구현
  backend/demo/src/main/java/store/oneul/mvc/payment/controller/PaymentController.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dao/PaymentDAO.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dto/CancelFailLogDTO.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dto/CancelRetryPayload.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dto/PaymentResultResponse.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dto/RefundReceiptDTO.java
  backend/demo/src/main/java/store/oneul/mvc/payment/enums/RefundReason.java
  backend/demo/src/main/java/store/oneul/mvc/payment/scheduler/ScheduledCancelRetryWorker.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/CancelDLQService.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/CancelDLQServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/CancelRetryService.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/CancelRetryServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/CompensationServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/PaymentStatusService.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/PaymentStatusServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/RefundReceiptService.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/RefundReceiptServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/TossCancelService.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/TossCancelServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/payment/usecase/PaymentUsecase.java
  backend/demo/src/main/resources/mappers/PaymentMapper.xml
Labels: 🗃️ BE

#211 [Design] 마이페이지 영수증 목록 퍼블리싱
  frontend/src/components/feed/FeedCreateBtn.tsx
  frontend/src/components/mypage/MyPage.tsx
  frontend/src/components/mypage/ReceiptList.tsx
  frontend/src/stores/receiptStore.tsx
  frontend/src/types/Receipt.ts
  frontend/src/utils/dataUtils.ts
Labels: 🖥️ FE, 🎨 Design

#212 [Feat] 유저 전체 결제 영수증 조회 API 구현
  backend/demo/src/main/java/store/oneul/mvc/payment/controller/PaymentController.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dao/PaymentDAO.java
  backend/demo/src/main/java/store/oneul/mvc/payment/dto/PaymentReceiptDTO.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/PaymentReceiptService.java
  backend/demo/src/main/java/store/oneul/mvc/payment/service/PaymentReceiptServiceImpl.java
  backend/demo/src/main/resources/mappers/PaymentMapper.xml
Labels: 🗃️ BE

#213 [Feat] 챌린지 피드 체크 컴포넌트 구현
  frontend/src/components/challengeDetail/ChallengeDetailPage.tsx
  frontend/src/components/challengeDetail/ChallengeFeed.tsx
  frontend/src/components/common/CheckStatus.tsx
  frontend/src/components/feedCheck/ChallengeFeedCheck.tsx
Labels: 🖥️ FE

#216 [Feat] 비로그인 유저 제한을 위한 ProtectedLayout 구현
  frontend/src/App.tsx
  frontend/src/components/login/LoginPage.tsx
  frontend/src/layouts/ProtectedLayout.tsx
  frontend/src/stores/userStore.tsx
Labels: 🖥️ FE

#217 [Fix] 챌린지 디테일 액티브 탭 이슈, 피드 체크 pending->approved 오류, 결제 오류 수정
  backend/demo/src/main/resources/mappers/PaymentMapper.xml
  frontend/src/components/challengeDetail/ChallengeDetailPage.tsx
  frontend/src/components/challengeDetail/ChallengeStatus.tsx
  frontend/src/components/challengeDetail/ChellengeDetail.tsx
  frontend/src/components/challengeRegist/ChallengeDetailModal.tsx
  frontend/src/components/feedCheck/ChallengeFeedCheck.tsx
Labels: 🖥️ FE, 🗃️ BE, :bug: Fix

#219 [Feat] 공통 not-found 페이지 구현, 챌린지 디테일 에러 분기 추가
  backend/demo/src/main/java/store/oneul/mvc/challenge/service/ChallengeServiceImpl.java
  backend/demo/src/main/java/store/oneul/mvc/common/exception/ForbiddenException.java
  backend/demo/src/main/java/store/oneul/mvc/config/ErrorCode.java
  backend/demo/src/main/java/store/oneul/mvc/config/GlobalExceptionHandler.java
  backend/demo/src/main/resources/mappers/ChallengeMapper.xml
  frontend/src/App.tsx
  frontend/src/components/challengeDetail/ChallengeDetailPage.tsx
  frontend/src/components/common/NotFoundPage.tsx
  frontend/src/hooks/useChallenge.ts
Labels: 🖥️ FE, 🗃️ BE, 🎨 Design
